### ISSUE TITLE
出现接口失效的故障

### ISSUE THREAD

**Issue by jscblack** [NorthCityChen/qingting#1]
![image](https://user-images.githubusercontent.com/33062157/76161426-61016680-616e-11ea-9c3d-717a1a6de5d7.png)
该错误可以复现

**Comment by NorthCityChen** [comment]
下次记得别在C盘运行程序就行

**Comment by jscblack** [comment]
![JYMB _9WV@MVZG8 IWPE6WC](https://user-images.githubusercontent.com/33062157/76161751-4aa8da00-6171-11ea-82de-267bbfeff6b7.png)
故障依旧存在
